services:
  db-metabase:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-dw:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_DW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DW_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DW_DB}
    volumes:
      - dw_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  metabase:
    image: metabase/metabase:v0.42.1
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: db-metabase
    ports:
      - "3000:3000"
    depends_on:
      - db-metabase
      - db-dw
volumes:
  db_data:
  dw_data:
